name: Frontend Deployment to ECS

on:
  push:
    branches: [ "master" ]  # 仅当 master 分支有提交时触发

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 检出当前的仓库代码

    # 部署到 ECS
    - name: Deploy frontend to ECS
      env:
        ECS_HOST: ${{ secrets.ECS_HOST }}         # ECS 的公网 IP
        ECS_USER: ${{ secrets.ECS_USER }}         # SSH 用户名
        ECS_KEY: ${{ secrets.ECS_KEY }}           # SSH 私钥
        APP_PATH: "/home/openutility_frontend"    # ECS 上的目标路径
      run: |
        # 添加私钥到 SSH 配置
        echo "${ECS_KEY}" > ecs_key.pem
        chmod 600 ecs_key.pem

        # 使用 ssh-keyscan 信任 ECS 主机
        mkdir -p ~/.ssh
        ssh-keyscan -H $ECS_HOST >> ~/.ssh/known_hosts

        # 确保远程路径存在，并清空旧内容
        ssh -i ecs_key.pem $ECS_USER@$ECS_HOST -tt "rm -rf $APP_PATH/* && mkdir -p $APP_PATH"
        docker restart nginx

        # 将本地仓库内容传输到远程服务器
        scp -r -i ecs_key.pem ./css ./html ./js $ECS_USER@$ECS_HOST:$APP_PATH

